language: python
python:
  #- "3.3"
  - "2.7"
  #- "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: python setup.py install
# command to run tests, e.g. python setup.py test
script:  python test/txt2unicode_tests.py 
